name: Update Commit Visualization

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-viz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas gitpython svgwrite plotly

      - name: Generate visualization
        run: python status_frequency_analysis.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add *.svg *.html
          git diff --staged --quiet || git commit -m "Update commit visualization"
          git push
